---
  swagger: "2.0"
  info:
    title: "TalkBirdy API"
    description: "Highly available concurrent speech pathology audio sample rating platform."
    version: "2.0.0"
  consumes:
    - application/json
  produces:
    - application/json